### PR TITLE
Fix actions

### LINKED ISSUE #64: Fix actions
In Mina, you can roughly match on an `actionState` precondition from any of the last 5 slots.
This doesn't hold for Zeko, instead we only allow matching on any of the last 5 `actionState`s,
with no regard for time. This is quite suboptimal.

### PR DESCRIPTION
**Pull request by L-as**
Each account has 5 action states, and an action state precondition can
match against any of them.
As time goes on, the action states are shifted backwards.
Thus, even if your proving takes a little while, you can match
against a somewhat recent historical action state.

The mechanism however relies on precise slots, which we don't have on Zeko.
However, we can let the sequencer choose when to do the shifting.
There is the possibility for abuse, but economically it would make
no sense for the sequencer, and any damage would be gone once
the next rational sequencer is elected.

We allow the prover to set this variable by passing in an "environment"
when proving. The code will call into the environment (represented as an
immediate object (class)), tell the sequencer what account is posting an action,
and the sequencer can respond back with whether to shift the action state or not.

The mechanism isn't integrated into the sequencer yet, it is merely exposed.
`of_zkapp_command_segment_exn` must not be used, instead `of_zkapp_command_segment_zeko_exn`
must be used.
The former uses a stub environment which always shifts.

For other functions there is an optional ?env parameter, which if ommitted,
is stubbed out in the same way.
Care must be taken to ensure that the same responses are given when proving and
when executing, otherwise proving can fail after accepting a command.

Untested, of course.

Closes issue #64

### CODE REVIEW

**Comment by L-as** [comment]
There’s some code duplication but I deemed it not worth the time to remove.

**Comment by L-as** [comment]
I added a test and tested this.

As I posted on the internal slack, I will hold off from implementing this in the sequencer just yet, since this interacts with the DA:
With this change, commands are _non-deterministic_. A command alone does not tell you what the output ledger is.
You need to know the non-deterministic choices made. In this case it's easier since it's a boolean choice between shifting and not shifting, but it still means changes to DA, and we're already in the process of replacing the DA.

Hence integrating this work into the sequencer will be done later.

File: src/lib/transaction_logic/mina_transaction_logic.ml [hunk 1]
```diff
@@ -248,6 +248,14 @@ module Transaction_applied = struct
         c.coinbase.status
 end
 
+(* ZEKO NOTE: issue #64 *)
+type env = < mark_shifted_and_get_previous_shiftedness : Account_id.t -> bool >
```
Comment (MartinOndejka) [inline src/lib/transaction_logic/mina_transaction_logic.ml:252]: why is this an object type?

Comment (MartinOndejka) [reply src/lib/transaction_logic/mina_transaction_logic.ml:252]: ah so that it has encapsulated state of shifts?

Comment (L-as) [reply src/lib/transaction_logic/mina_transaction_logic.ml:252]: Immediate objects are anonymous records. I define env type many types, and this means they are all equal.
If I just used a record, they would be incompatible, and it would mean you would need to specify which you mean when implementing the env. 

Another solution is to define a normal record in a single place.
