### PR TITLE
Fix the zkapp command signature bug

### LINKED ISSUE #131: Unify the payment and zkapp command logic in sequencer
Currently there are 2 functions `apply_signed_command` and `apply_zkapp_command`. The logic can be unified to the one function `apply_user_command`.

### PR DESCRIPTION
**Pull request by MartinOndejka**
Before the sequencer was checking for valid signature only for signed commands as I thought the zkapp command logic checks to signature automatically. [As it turns out](https://github.com/zeko-labs/zeko/blob/main-berkeley/src/lib/transaction_logic/mina_transaction_logic.ml#L1696-L1697) zkapp command logic omits the authorization check so this PR fixes it by unifying logic for signed commands and zkapp commands under the `User_command.check`.

This PR also adds useful CLI commands for manipulation of proving queue.

Closes #131

### CODE REVIEW

File: src/app/zeko/sequencer/lib/zeko_sequencer.ml [hunk 1]
```diff
@@ -694,7 +656,7 @@ module Sequencer = struct
     let _, command_witness =
       Result.ok_exn
       @@ Result.map_error ~f:Error.to_exn
-      @@ apply_zkapp_command t command
+      @@ apply_user_command t (Zkapp_command command)
```
Comment (L-as) [inline src/app/zeko/sequencer/lib/zeko_sequencer.ml:651]: Is a user command a signed or zkapp command?

File: src/app/zeko/sequencer/lib/zeko_sequencer.ml [hunk 2]
```diff
@@ -754,15 +716,8 @@ module Sequencer = struct
     in
     printf "Applying %d commands\n%!" (List.length commands) ;
     List.iter commands ~f:(fun command ->
-        match command with
-        | User_command.Signed_command signed_command ->
-            let _res =
-              apply_signed_command t signed_command |> Or_error.ok_exn
-            in
-            ()
-        | User_command.Zkapp_command zkapp_command ->
```
Comment (L-as) [inline src/app/zeko/sequencer/lib/zeko_sequencer.ml:763]: Ah, I see

**Review by L-as — CHANGES_REQUESTED** [review]
Could you add a more detailed commit message and PR description? Force push here is OK since it’s a feature branch. 
You could switch zeko machine to this branch while doing this.

**Review by L-as — APPROVED** [review]
Thanks
